// @generated
// This file is @generated by prost-build.
/// Events 消息，表示一组以太坊事件
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    /// 包含多个 Event，每个 Event 表示一个事件
    #[prost(message, repeated, tag="1")]
    pub events: ::prost::alloc::vec::Vec<Event>,
}
/// Event 消息，定义单个以太坊事件的结构
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Event {
    /// 事件发生的合约地址
    #[prost(string, tag="1")]
    pub address: ::prost::alloc::string::String,
    /// 事件的主题数组（用于事件过滤）
    #[prost(string, repeated, tag="2")]
    pub topics: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 事件所属的交易哈希
    #[prost(string, tag="3")]
    pub tx_hash: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
