// @generated
// This file is @generated by prost-build.
/// BlockMeta 消息，表示以太坊区块的元数据
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockMeta {
    /// 区块高度（区块编号）
    #[prost(uint64, tag="1")]
    pub number: u64,
    /// 当前区块的哈希值
    #[prost(string, tag="2")]
    pub hash: ::prost::alloc::string::String,
    /// 父区块的哈希值
    #[prost(string, tag="3")]
    pub parent_hash: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
